# Generated by Django 5.2.1 on 2025-05-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('rated', models.CharField(blank=True, max_length=100)),
                ('released', models.CharField(blank=True, max_length=100)),
                ('runtime', models.CharField(blank=True, max_length=100)),
                ('director', models.CharField(blank=True, max_length=100)),
                ('writer', models.CharField(blank=True, max_length=100)),
                ('plot', models.CharField(blank=True, max_length=1000)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('awards', models.CharField(blank=True, max_length=100)),
                ('poster', models.ImageField(blank=True, upload_to='movies')),
                ('poster_url', models.URLField(blank=True)),
                ('metascore', models.CharField(blank=True, max_length=100)),
                ('imdbRating', models.CharField(blank=True, max_length=100)),
                ('imdbVotes', models.CharField(blank=True, max_length=100)),
                ('imdbID', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('dvd', models.CharField(blank=True, max_length=100)),
                ('boxOffice', models.CharField(blank=True, max_length=100)),
                ('production', models.CharField(blank=True, max_length=100)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('totalSeasons', models.CharField(blank=True, max_length=100)),
                ('actors', models.ManyToManyField(blank=True, to='actor.actor')),
                ('genre', models.ManyToManyField(blank=True, to='movia.genre')),
                ('ratings', models.ManyToManyField(blank=True, to='movia.rating')),
            ],
        ),
    ]
