# Generated by Django 5.2.1 on 2025-06-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='totalSeasons',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
