# Generated by Django 5.2.1 on 2025-06-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movia', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Terrible'), (2, 'Bad'), (3, 'Poor'), (4, 'Mediocre'), (5, 'Watchable'), (6, 'Average'), (7, 'Good'), (8, 'Very Good'), (9, 'Excellent'), (10, 'Masterpiece')]),
        ),
    ]
